</$objtype/mkfile

TARG=svcfs
OFILES=svcfs.$O\

HFILES=\
	service.h\

BIN=/$objtype/bin/aux
LIB=../lib.$O.a

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\

</sys/src/cmd/mkone

$LIB:
	cd ../libservice
	mk

$O.svcfs: svcfs.$O $LIB
	$LD -o $target $prereq

CFLAGS=$CFLAGS -I..

