</$objtype/mkfile

LIB=../lib.$O.a
OFILES=\
	svcdial.$O\
	svcquery.$O\
	svctimefmt.$O\
	svcfree.$O\

HFILES=\
	../service.h

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\

</sys/src/cmd/mksyslib
CFLAGS=$CFLAGS -I..
